version: 2.1
jobs:
  build_and_test:
    filters:
      branches:
        only: develop
    docker:
      - image: circleci/python:3.8.0rc1
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt --user
      - run:
          name: Install package
          command: pip install . --user
      - run:
          name: Unit tests
          command: |
            pip install pytest --user
            pip install pytest-cov --user
            pip install codecov --user
            pytest --cov ./
            codecov
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
